### ISSUE TITLE
getting an error from my console while trying to use the lesson skipper

### ISSUE THREAD

**Issue by Subject1494** [ArjhanToteck/iReady-Overload#2]
like the title says, i'll get the error after pasting lesson.js into the console after opening a lesson. any help would be greatly appreciated!
![image](https://user-images.githubusercontent.com/76988729/118701575-dbe9f680-b7e1-11eb-9add-bda0be7fedad.png)

**Comment by ArjhanToteck** [comment]
Can you show the request and console? The problem might be on either of those.

**Comment by Subject1494** [comment]
sure! i'll try my best, im not the best at this. thank you again

![image](https://user-images.githubusercontent.com/76988729/118731793-25990800-b807-11eb-9b53-9530b7e57df3.png)

**Comment by isaiahroblox** [comment]
@ArjhanToteck when will you make the  i-Ready Diagnostic
