### ISSUE TITLE
lessonViewer does not work

### ISSUE THREAD

**Issue by CoolCoderTech** [ArjhanToteck/iReady-Overload#3]
Google says that it has been blocked

**Comment by ArjhanToteck** [comment]
Copy the link and open it in a new tab.

**Comment by CoolCoderTech** [comment]
It still does not work

**Comment by ArjhanToteck** [comment]
OK well tell me exactly what you have tried, and maybe send a screenshot of the message.

**Comment by CoolCoderTech** [comment]
I tried to open it.
![blocked-extension](https://user-images.githubusercontent.com/83834491/119023082-5d22c400-b96f-11eb-9226-e40be3446339.png)

**Comment by CoolCoderTech** [comment]
but I don't have any extensions except for iReady Overload

**Comment by ArjhanToteck** [comment]
Error should be fixed in new update, reinstall the chrome extension from chromeExtension.zip.
