### ISSUE TITLE
any way to make a bookmarklet?

### ISSUE THREAD

**Issue by F1R3L1GHT** [ArjhanToteck/iReady-Overload#4]
any way to make a bookmarklet? i can do tthis on my mac but not chromebook cus teacher blocked inspect element

**Comment by ArjhanToteck** [comment]
Bookmark this: 

`javascript:void%20function(){function%20a(a){for(var%20b,d=a+%22=%22,e=decodeURIComponent(document.cookie),f=e.split(%22;%22),g=0;g%3Cf.length;g++){for(b=f[g];%22%20%22==b.charAt(0);)b=b.substring(1);if(0==b.indexOf(d))return%20b.substring(d.length,b.length)}return%22%22}var%20b=`chrome-extension://${chrome.runtime.id}/lessonViewer.html`,c=document.createElement(%22div%22);c.innerHTML=`
	%3Cdiv%20style=%22width:300px;%20left:%201px;%20top:%201px;%20background-color:%20%23282828;%20color:%20white;%20outline:%20white%20solid%201px;%20position:absolute;%20z-index:%2099999;%22%3E
		%3Ch1%20style=%22font-size:%2032px;%22%3EiReady%20Overload%3C/h1%3E

		%3Cbr%3E

		%3Ch2%20style=%22font-size:%2025px;%20font-style:%20normal%20!important;%20color:%20white%20!important;%22%3ELesson%20Skipper%3C/h2%3E

		%3Cbutton%20onclick=%22skipLesson()%22%3ESkip%20current%20lesson%3C/button%3E

		%3Cbr%3E
		%3Cbr%3E

		%3Ch2%20style=%22font-size:%2025px;%20font-style:%20normal%20!important;%20color:%20white%20!important;%22%3EMinutes%20Hack%3C/h2%3E

		%3Cbutton%20onclick=%22farmMinutes(this)%22%3EFarm%20minutes%3C/button%3E

%20%20%20%20%3Cbr%3E
		%3Cbr%3E

		%3Ch2%20style=%22font-size:%2025px;%20font-style:%20normal%20!important;%20color:%20white%20!important;%22%3EDiagnostic%20Hack%3C/h2%3E

		%3Cbutton%20onclick=%22diagnosticHack(this)%22%3EEnable%20hack%3C/button%3E


				%3Cbr%3E
		%3Cbr%3E
		
		%3Ch2%20style=%22font-size:%2025px;%20font-style:%20normal%20!important;%20color:%20white%20!important;%22%3ELesson%20Viewer%3C/h2%3E
		%3Cbr%3E
		This%20tool%20searches%20through%20all%20known%20iReady%20lessons%20and%20their%20files.%20Go%20%3Ca%20href=%22https://i-ready.com/lessonViewer%22%3Ehere%3C/a%3E%20to%20access%20the%20tool.

		%3Cbr%3E
		%3Cbr%3E
		
		%3Chr%3E
		This%20tool%20was%20created%20by%20%3Ca%20href=%22https://github.com/ArjhanToteck/iReady-Overload%22%3EArjhanToteck%3C/a%3E.
		
		%3Cbr%3E
		%3Cbr%3E
	%3C/div%3E`;var%20d=document.createElement(%22script%22);d.innerHTML=`var%20minuteFarming%20=%20false;%20${function(){if(!window.html5Iframe)alert(%22You%20do%20not%20have%20a%20lesson%20currently%20open.%20You%20must%20open%20a%20lesson%20to%20skip%20it.%22);else{var%20a=html5Iframe.src.split(%22%3Fcsid=%22)[1].split(%22%26type%22)[0],b=a.includes(%2210_%22)%3Fnull:prompt(%22Quiz%20detected.%20What%20score%20would%20you%20like%20(out%20of%20100)%3F%22,100),c=a.includes(%2210_%22)%3Fnull:`{%22score%22:${b}}`;fetch(%22https://login.i-ready.com/student/lesson/componentCompleted%22,{headers:{accept:%22*/*%22,%22accept-language%22:%22en-US,en;q=0.9%22,%22content-type%22:%22application/json;charset=UTF-8%22,%22sec-fetch-dest%22:%22empty%22,%22sec-fetch-mode%22:%22cors%22,%22sec-fetch-site%22:%22same-origin%22,%22sec-gpc%22:%221%22},referrer:%22https://login.i-ready.com/student/dashboard/home%22,referrerPolicy:%22strict-origin-when-cross-origin%22,body:`{\%22componentStatusId\%22:\%22${a}\%22,\%22instructionLessonOutcome\%22:${c}}`,method:%22POST%22,mode:%22cors%22,credentials:%22include%22}),alert(%22Close%20the%20lesson/quiz%20and%20you%20should%20see%20it%20was%20skipped.%22)}}.toString()}%20\n%20${function(b){if(minuteFarming%26%26(c=a(%22csid%22),fetch(`https://login.i-ready.com/student/v1/web/lesson_component/${c}%3Faction=pause`,{headers:{accept:%22application/json,%20text/plain,%20*/*%22,%22accept-language%22:%22en-US,en;q=0.9%22,%22sec-fetch-dest%22:%22empty%22,%22sec-fetch-mode%22:%22cors%22,%22sec-fetch-site%22:%22same-origin%22},referrer:%22https://login.i-ready.com/student/dashboard/home%22,referrerPolicy:%22strict-origin-when-cross-origin%22,body:null,method:%22GET%22,mode:%22cors%22,credentials:%22include%22}),document.cookie=`csid=;%20expires=Thu,%2018%20Dec%201970%2012:00:00%20UTC%22`,b.innerText=%22Farm%20minutes%22,minuteFarming=!1,alert(%22The%20minutes%20should%20now%20be%20in%20your%20account.%22)),!!window.html5Iframe){var%20c=html5Iframe.src.split(%22%3Fcsid=%22)[1].split(%22%26type%22)[0];document.cookie=`csid=${c};%20expires=Thu,%2018%20Dec%202999%2012:00:00%20UTC%22`,document.cookie=`minutes=${45};%20expires=Thu,%2018%20Dec%202999%2012:00:00%20UTC%22`,alert(%22Neccessary%20data%20to%20farm%20minutes%20have%20now%20been%20collected.%20To%20begin%20farming%20minutes,%20go%20to%20the%20iReady%20menu%20by%20closing%20this%20lesson/quiz.%20Then,%20press%20this%20button%20again.%22)}else%20a(%22csid%22)%3F(c=a(%22csid%22),fetch(`https://login.i-ready.com/student/v1/web/lesson_component/${c}%3Faction=resume`,{headers:{accept:%22application/json,%20text/plain,%20*/*%22,%22accept-language%22:%22en-US,en;q=0.9%22,%22sec-fetch-dest%22:%22empty%22,%22sec-fetch-mode%22:%22cors%22,%22sec-fetch-site%22:%22same-origin%22},referrer:%22https://login.i-ready.com/student/dashboard/home%22,referrerPolicy:%22strict-origin-when-cross-origin%22,body:null,method:%22GET%22,mode:%22cors%22,credentials:%22include%22}),minuteFarming=!0,b.innerText=%22Stop%20farming%20minutes%22,alert(%22The%20minute%20farming%20proccess%20has%20now%20begun.%20Do%20not%20close%20this%20page.%20Do%20not%20turn%20off%20your%20computer.%20After%20you%20press%20\%22ok,\%22%20every%20minute%20that%20passes%20will%20be%20added%20to%20your%20account.%20When%20you%20want%20to%20stop%20the%20timer%20and%20add%20the%20farmed%20minutes%20to%20your%20account,%20press%20the%20button%20labeled%20\%22Stop%20farming%20minutes\%22.%20Press%20\%22ok\%22%20to%20begin.%22)):alert(%22You%20do%20not%20have%20a%20lesson%20currently%20open.%20You%20must%20open%20a%20lesson%20to%20begin%20the%20proccess.%22)}.toString()}%20\n%20${function(a){if(!!XMLHttpRequest.prototype.realSend)XMLHttpRequest.prototype.send=XMLHttpRequest.prototype.realSend,XMLHttpRequest.prototype.realSend=void%200,alert(%22Hack%20was%20disabled.%22),a.innerText=%22Enable%20hack%22;else%20if(%22undefined%22==typeof%20diagnosticIFrame)alert(%22Diagnostic%20not%20detected.%20Open%20the%20diagnostic%20first%20to%20use%20the%20hack.%22);else%20if(!XMLHttpRequest.prototype.realSend){XMLHttpRequest.prototype.realSend=XMLHttpRequest.prototype.send,XMLHttpRequest.prototype.send=function(a){newBody=JSON.parse(a),!1==newBody.correct%26%26(newBody.correct=!0),null!=newBody.durationSeconds%26%26(newBody.durationSeconds=1000),this.realSend(JSON.stringify(newBody))},alert(%22Hack%20was%20enabled.%20All%20answers%20inputted%20in%20diagnostic%20will%20be%20correct.%20Please%20do%20not%20answer%20questions%20too%20fast%20or%20your%20test%20will%20be%20marked%20as%20rushed.%22),a.innerText=%22Disable%20hack%22}}.toString()}%20\n%20${a.toString()}%20\n`,document.body.appendChild(d),function(a){function%20b(a){a=a||window.event,a.preventDefault(),h=a.clientX,i=a.clientY,document.onmouseup=d,document.onmousemove=c}function%20c(b){b=b||window.event,b.preventDefault(),f=h-b.clientX,g=i-b.clientY,h=b.clientX,i=b.clientY,a.style.top=a.offsetTop-g+%22px%22,a.style.left=a.offsetLeft-f+%22px%22}function%20d(){document.onmouseup=null,document.onmousemove=null}var%20f=0,g=0,h=0,i=0;document.getElementById(a.id+%22header%22)%3Fdocument.getElementById(a.id+%22header%22).onmousedown=b:a.onmousedown=b}(c.firstElementChild),document.body.appendChild(c)}();`

**Comment by F1R3L1GHT** [comment]
the lesson skipper doesnt work :/

**Comment by F1R3L1GHT** [comment]
i only need the lesson skipper rn sooo can u just make a seperate on for lesson skipping?

**Comment by ArjhanToteck** [comment]
Sure, here it is:

`javascript:void%20function(){var%20a=html5Iframe.src.split(%22%3Fcsid=%22)[1].split(%22%26type%22)[0],b=a.includes(%2210_%22)%3Fnull:%22{\%22score\%22:100}%22;fetch(%22https://login.i-ready.com/student/lesson/componentCompleted%22,{headers:{accept:%22*/*%22,%22accept-language%22:%22en-US,en;q=0.9%22,%22content-type%22:%22application/json;charset=UTF-8%22,%22sec-fetch-dest%22:%22empty%22,%22sec-fetch-mode%22:%22cors%22,%22sec-fetch-site%22:%22same-origin%22,%22sec-gpc%22:%221%22},referrer:%22https://login.i-ready.com/student/dashboard/home%22,referrerPolicy:%22strict-origin-when-cross-origin%22,body:`{\%22componentStatusId\%22:\%22${a}\%22,\%22instructionLessonOutcome\%22:${b}}`,method:%22POST%22,mode:%22cors%22,credentials:%22include%22})}();`

**Comment by F1R3L1GHT** [comment]
it doesnt work - i made a working one, here it is javascript:(function()%7Bvar%20csid%20%3D%20html5Iframe.src.split(%22%3Fcsid%3D%22)%5B1%5D.split(%22%26type%22)%5B0%5D%3Bvar%20score%20%3D%20csid.includes(%2210_%22)%20%3F%20null%20%3A%20%22%7B%5C%22score%5C%22%3A100%7D%22%3Bfetch(%22https%3A%2F%2Flogin.i-ready.com%2Fstudent%2Flesson%2FcomponentCompleted%22%2C%20%7B%22headers%22%3A%20%7B%22accept%22%3A%20%22*%2F*%22%2C%22accept-language%22%3A%20%22en-US%2Cen%3Bq%3D0.9%22%2C%22content-type%22%3A%20%22application%2Fjson%3Bcharset%3DUTF-8%22%2C%22sec-fetch-dest%22%3A%20%22empty%22%2C%22sec-fetch-mode%22%3A%20%22cors%22%2C%22sec-fetch-site%22%3A%20%22same-origin%22%2C%22sec-gpc%22%3A%20%221%22%7D%2C%22referrer%22%3A%20%22https%3A%2F%2Flogin.i-ready.com%2Fstudent%2Fdashboard%2Fhome%22%2C%22referrerPolicy%22%3A%20%22strict-origin-when-cross-origin%22%2C%22body%22%3A%20%60%7B%5C%22componentStatusId%5C%22%3A%5C%22%24%7Bcsid%7D%5C%22%2C%5C%22instructionLessonOutcome%5C%22%3A%24%7Bscore%7D%7D%60%2C%22method%22%3A%20%22POST%22%2C%22mode%22%3A%20%22cors%22%2C%22credentials%22%3A%20%22include%22%7D)%7D)()

**Comment by F1R3L1GHT** [comment]
also, im trying to remake the ui that has the buttons on it, but idk how to make the <div>, it shows up on the place where u view ur progress, but not in a lesson, can you give me an example?
