### ISSUE TITLE
The new lesson skipper doesnt work.

### ISSUE THREAD

**Issue by Phenomenon1337** [ArjhanToteck/iReady-Overload#6]
The new lesson skipper doesnt work :/

**Comment by ArjhanToteck** [comment]
You have to be more detailed than that if you want me to help. The lesson skipper does work, I tested it just today. Do any errors come up in the console? Where did you paste the code? At what point did you paste the code? Did you make sure to press enter after pasting the code?

**Comment by F1R3L1GHT** [comment]
I made a bookmarklet with https://mrcoles.com/bookmarklet/, i didn't see the console, ill check it later :)
